# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from seq2seq.Seq2Seq_model import seq2seq
from ner import ner_class
from intent_data.intent_cl import Intent_model


class Ui_MainWindow():

    def __init__(self):
        self.test = 1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(347, 384, 104, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.btntest)
        self.pushButton.setStyleSheet("color: blue;"
                               "background-color: #87CEFA;"
                               "border-style: dashed;"
                               "border-width: 3px;"
                               "border-color: #1E90FF;"
                                "border-top-right-radius: 5px; "
                                "border-bottom-right-radius: 5px; "
                                "margin-left:-3px;"
                                    )

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 451, 381))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setStyleSheet(
                                       #"background: url('./img/tb_bg.jpg');"
                                       "border-color: #1E90FF;"
                                       "border-style: solid;"
                                       )

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1, 385, 350, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.returnPressed.connect(self.sendtxt)
        self.lineEdit.setStyleSheet("color: blue;"
                               "background-color: #87CEFA;"
                               "border-style: dashed;"
                               "border-width: 3px;"
                               "border-color: #1E90FF;"
                                "border-top-left-radius: 5px;"
                                "border-bottom-left-radius: 5px;"
                                "margin-right:-4px"
                                    )


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 454, 21))
        self.menubar.setObjectName("menubar")
        self.menuChatBot = QtWidgets.QMenu(self.menubar)
        self.menuChatBot.setObjectName("menuChatBot")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuChatBot.menuAction())

        self.initAction = QtWidgets.QAction(MainWindow)
        self.initAction.setObjectName('initAction')
        self.initAction.setShortcut("Ctrl+N")
        self.initAction.setStatusTip('TextBrowser Reset')
        self.initAction.triggered.connect(self.init_application)
        self.menuChatBot.addAction(self.initAction)

        self.closeAction = QtWidgets.QAction(MainWindow)
        self.closeAction.setObjectName('closeAction')
        self.closeAction.setShortcut("Ctrl+Q")
        self.closeAction.setStatusTip('End application')
        self.closeAction.triggered.connect(self.close_application)
        self.menuChatBot.addAction(self.closeAction)

        self.helpAction = QtWidgets.QAction(MainWindow)
        self.helpAction.setObjectName('helpAction')
        self.helpAction.setShortcut("Ctrl+H")
        self.helpAction.setStatusTip('Help')
        self.helpAction.triggered.connect(self.help_application)
        self.menuChatBot.addAction(self.helpAction)


        self.retranslateUi(MainWindow)
        MainWindow.setFixedSize(454,508)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def help_application(self):
        self.textBrowser.append('날씨와 뉴스,버스확인 및 간단한 일상대화가 가능합니다.')
        self.textBrowser.append('')
        self.textBrowser.append('1. 날씨 - 위치,날짜 정보가 필요합니다. (Google Weather)')
        self.textBrowser.append('2. 뉴스 - 카테고리 정보로 필요한 뉴스만 가져옵니다. (Naver News)')
        self.textBrowser.append('3. 버스 - 현재 얼마나 남았는지 확인합니다. (API)')

    def close_application(self):
        print("Close!")
        sys.exit()

    def init_application(self):
        self.textBrowser.clear()

    def sendtxt(self):
        txt = self.lineEdit.text()
        txt2 = '왜 안되는거야 '

        # txt_tq1 = "<table width='99%' height='100' background='./ner/img/chat_img.png'><tr><td style='text-align:left;'>나 : "+txt2+"</td></tr></table>"
        # txt_ta1 = "<table border='1' width='99%'><tr><td style='text-align:right;'>table은 어때 : 너</td></tr></table>"
        # txt_tq2 = "<table border='1' width='99%'><tr><td style='text-align:left;'>나 : " + txt + "</td></tr></table>"
        #
        # txt_w = "<table width='150px' border='1' bordercolor='red' style='background-color:pink;border-radius:25px 25px;padding:5px 5px 5px 5px;'><tr><td colspan='2'><b><font size='4'>위치</font></b></td></tr><tr><td colspan='2'><b><font size='3' color='gray'>요일</font></b></td></tr><tr><td rowspan='2'><img style='float:left;height:64px;width:64px' src='C:/Users/admin/PycharmProjects/new_seq/ner/img/구름 조금.png' data-atf='1'></td><td><font size='3'>구름 조금</font></td></tr><tr><td><b><font size='5'>11</font> <font color='red'>°C</font></b></td></tr><tr><td colspan='2'><ul style='list-style:none;'><li><font size='3' color='gray'>강수확률 : 100</font></li><li><font size='3' color='gray'>습도 : 3</font></li><li><font size='3' color='gray'>풍속 : 8</font></li></ul></td></tr></table>"
        # txt_ta2 = "<table border='1' width='99%'><tr><td style='float:right;text-align:right;'> : 너" + txt_w + "</td></tr></table>"
        #
        # self.textBrowser.append(txt_tq1)
        # self.textBrowser.append(txt_ta1)
        # self.textBrowser.append(txt_tq2)
        # self.textBrowser.append(txt_ta2)

        # q1 = "<table width='99%'><tr><td><ul><li style = 'border:solid 1px;color:white;padding:.5em;list-style:none;float:left;clear:both;background:blue;'> aaa</li></ul></table></tr></td>"
        # a1 = "<table width='99%'><tr><td><ul><li style = 'border:solid 1px;color:white;padding:.5em;list-style:none;float:right;clear:both;background:green;'> bbb</li></ul></table></tr></td>"

        q1 = "<table width='99%' style = 'margin-bottom:8px;border-collapse:collapse;border-color:#9ABAD9;border-spacing:0'> <tbody><tr><td width='7%' valign='top'><img width='45' height='50' src='./ner/img/c_icon1.png'></td><td style='max-width:60%;background-color:#ffc702;border-color:#9ABAD9;border-style:solid;border-width:1px;color:#000000;font-family:'Courier New', Courier, monospace !important;;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal;' valign='middle'>&nbsp;안녕 너는 누구니? </td><td></td></tr></tbody></table>"
        a1 = "<table width='99%' style = 'margin-bottom:12px;border-collapse:collapse;border-color:#9ABAD9;border-spacing:0'> <tbody><tr><td width='33%'></td><td class='bradius' style='max-width:60%;background-color:#ffc702;border-color:#68cbd0;border-style:solid;border-width:1px;color:#000000;font-family:'Courier New', Courier, monospace !important;;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal;' valign='middle'>&nbsp;저는 신디 Bot 입니다.</td><td width='7%' valign='top'><img width='45' height='50' src='./ner/img/ai_img2.png'></td></tr></tbody></table>"

        weather_txt = "<table width='80%' height='80%' style='margin-bottom:2px;border-color:#9ABAD9;background-color:snow;padding:5px 5px 5px 5px;'><tr><td colspan='2'><b><font size='4'>위치</font></b></td></tr><tr><td colspan='2'><b><font size='3' color='gray'>요일</font></b></td></tr><tr><td rowspan='2'><img style='float:left;height:64px;width:64px' src='C:/Users/admin/PycharmProjects/new_seq/ner/img/강우(천둥, 번개 동반).png' data-atf='1'></td><td><font size='3'>강우(천둥, 번개 동반)</font></td></tr><tr><td><b><font size='5'>30</font> <font color='red'>°C</font></b></td></tr><tr><td colspan='2'><ul style='list-style:none;'><li><font size='3' color='gray'>강수확률 : 90%</font></li><li><font size='3' color='gray'>습도 : 90%</font></li><li><font size='3' color='gray'>풍속 : 8m/s</font></li></ul></td></tr></table>"
        a2 = "<table width='99%' style = 'margin-bottom:5px;border-collapse:collapse;border-color:#9ABAD9;border-spacing:0'> <tbody><tr><td width='70%'></td><td style='max-width:23%;background-color:#ffc702;border-color:#68cbd0;border-style:solid;border-width:1px;color:#000000;font-family:'Courier New', Courier, monospace !important;;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal;' align='center'>" + weather_txt + "</td><td width='7%' valign='top'><img width='45' height='50' src='./ner/img/ai_img2.png'></td></tr></tbody></table>"

        self.textBrowser.append(q1)
        self.textBrowser.append(a1)
        self.textBrowser.append(a2)

        self.lineEdit.clear()
        #self.lineEdit.setText(self.textBrowser.toHtml())

    def btntest(self):
        self.textBrowser.setText(self.textBrowser.toHtml())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "아무거나"))
        self.pushButton.setText(_translate("MainWindow", "전송"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' 'http://www.w3.org/TR/REC-html40/strict.dtd'>\n"
"<html><head><meta name='qrichtext' content='1' /><style type='text/css'>\n"
"p, li { white-space: pre-wrap; }\n td { border:1px solid; border-top-left: 20px; }\n"
"</style></head><body style='font-size:9pt; font-weight:400; font-style:normal;'>\n"
"<p style='-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'><br /></p></body></html>"))
        self.menuChatBot.setTitle(_translate("MainWindow", "신디 BOT"))
        self.initAction.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.initAction.setText(_translate("MainWindow", "화면 정리(Clear)"))
        self.closeAction.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.closeAction.setText(_translate("MainWindow", "프로그램 종료(Exit)"))
        self.helpAction.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.helpAction.setText(_translate("MainWindow", "도움말(Help)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
